### ISSUE TITLE
Meteor release >=1.0.4. Raise error "MongoError: '$set' is empty."

### ISSUE THREAD

**Issue by osv** [aldeed/meteor-collection2#200]
When I update collection field with empty value I get error "MongoError: '$set' is empty. You must specify a field like so: {$mod: {<field>: ...}}"

Can be reproduced in meteor 1.0.4, 1.0.5. Meteor@1.0.3.2 work without error, example code:

```js
var Schema = new SimpleSchema({
  name: {
    type: String,
    optional: true
  }
});

Collection = new Meteor.Collection('collection');
// when you attach, update $set: {xxx: ''} not working
Collection.attachSchema(Schema);

if (Meteor.isServer) {
  Meteor.startup(function () {
    console.log('insert document');
    var id  = Collection.insert({name: ''});
    console.log('update doc %s', id);
    Collection.update(id, {$set: {name: ''}});
    //   _______________________________^^
    //  / Error raise:  MongoError: '$set' is empty.
    // / You must specify a field like so: {$mod: {<field>: ...}}
  });
}
```
If you comment `Collection.attachSchema(Schema);` document updated without error

**Comment by aldeed** [comment]
This was an issue in simple-schema code, fixed in https://github.com/aldeed/meteor-simple-schema/commit/9697e946011110b8bc662f2032bb08c370ac6f11

It was always an issue, but Mongo used to ignore empty objects whereas Mongo 2.6+ throws the error.

**Comment by osv** [comment]
Thanks for fast fix and explain!

**Comment by Praxie** [comment]
I have a similar issue with $push operator. Package update doesn't solve the problem.
$set works.

**Comment by aldeed** [comment]
@Praxie please submit a new issue with code that reproduces the error. That fix should work for all operators, but maybe there's something else going on.

**Comment by Praxie** [comment]
@aldeed I don't know if that worth the issue.
The problem is with this validator - Match.OneOf([], [String]). 

```javascript
areTyping: {
    type: Match.OneOf([], [String]),
    label: "Ids of users that are typing",
},
```

It works with 
```javascript
areTyping: {
    type: [String],
    label: "Ids of users that are typing",
},
```

**Comment by aldeed** [comment]
simple schema does not support using `Match` types. You don't need it because empty arrays are fine by default unless you specify `minCount: 1`.

**Comment by Praxie** [comment]
@aldeed thanks!
