### ISSUE TITLE
$unset not allowed on fields not in schema

### ISSUE THREAD

**Issue by BudgieInWA** [aldeed/meteor-collection2#295]
Collection2 causes an update to fail if the update contains a `$unset` modifier that references a field that is not in the schema.

This is annoying when the schema has changed and was unexpected to me.

**Comment by aldeed** [comment]
Pretty sure this was fixed a long time ago in simple-schema package. Make sure your app is pulling in the latest simple-schema version.

**Comment by barisro** [comment]
I have collection2 version 2.10.0 and simple-schema 1.5.3 but still have the problem.

**Comment by s-devaney** [comment]
+1
